"use client";
import Link from "next/link";
import { CheckCircle2, Download, Loader2, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api-client";
import { ENGLISH_LEVELS, type EnglishLevel } from "@/lib/levels";
import { useDemo } from "@/lib/demo-store";

type Profile={nativeLanguage:string;explanationLanguage:string;selfAssessedLevel?:EnglishLevel;currentLevel?:EnglishLevel;weeklyMinutes:number;englishWeeklyMinutes?:number;germanWeeklyMinutes?:number;mentorStyle:string;correctionIntensity:number;interests:string[];occupation?:string};
type Consent={type:string;granted:boolean};
type Memory={id:string;type:string;status:string;key:string;value:string;confidence?:number};
type PrivacyRequest={id:string;type:string;status:string;requestedAt:string};
type Tab="learning"|"memory"|"privacy";

export default function SettingsPage(){
 const [tab,setTab]=useState<Tab>("learning");const [profile,setProfile]=useState<Profile|null>(null);const [consents,setConsents]=useState<Record<string,boolean>>({});const [memories,setMemories]=useState<Memory[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [deleteConfirm,setDeleteConfirm]=useState("");
 const {changeLevel,learningLanguage,level}=useDemo();const language=learningLanguage==="de"?"de":"en";
 useEffect(()=>{Promise.all([api.get<Profile>("/learner-profile"),api.get<Consent[]>("/me/consents"),api.get<Memory[]>("/learner-profile/memories")]).then(([p,c,m])=>{setProfile({...p,interests:p.interests??[]});setConsents(Object.fromEntries(c.map(item=>[item.type,item.granted])));setMemories(m)}).catch((e:ApiError)=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function saveProfile(){if(!profile)return;setSaving(true);setError("");setMessage("");const weeklyMinutes=(language==="de"?profile.germanWeeklyMinutes:profile.englishWeeklyMinutes)??profile.weeklyMinutes;try{const updated=await api.put<Profile>("/learner-profile",{nativeLanguage:profile.nativeLanguage||"pl",explanationLanguage:profile.explanationLanguage||"pl",weeklyMinutes:Number(weeklyMinutes),mentorStyle:profile.mentorStyle,correctionIntensity:Number(profile.correctionIntensity),interests:profile.interests,occupation:profile.occupation||undefined});await Promise.all([api.put("/learner-profile/level",{language,level}),api.put("/learner-profile/goal",{language,weeklyMinutes:Number(weeklyMinutes)})]);setProfile({...updated,[language==="de"?"germanWeeklyMinutes":"englishWeeklyMinutes"]:weeklyMinutes});setMessage(`Preferencje, poziom i cel ${language==="de"?"niemieckiego":"angielskiego"} zostały zapisane.`)}catch(e){setError(e instanceof ApiError?e.message:"Nie udało się zapisać preferencji.")}finally{setSaving(false)}}
 async function setConsent(type:string,granted:boolean){setError("");try{await api.put("/me/consents/"+type,{granted,policyVersion:"2026-08"});setConsents(current=>({...current,[type]:granted}));setMessage("Ustawienie prywatności zostało zapisane.")}catch(e){setError(e instanceof ApiError?e.message:"Nie udało się zapisać zgody.")}}
 async function deleteMemory(id:string){setError("");try{await api.delete("/learner-profile/memories/"+id);setMemories(items=>items.filter(item=>item.id!==id));setMessage("Pamięć mentora została usunięta.")}catch(e){setError(e instanceof ApiError?e.message:"Nie udało się usunąć pamięci.")}}
 async function privacyRequest(type:"EXPORT"|"DELETE_ACCOUNT"){setSaving(true);setError("");setMessage("");try{const request=await api.post<PrivacyRequest>("/me/privacy-requests",{type});setMessage(type==="EXPORT"?"Eksport danych został zlecony. Numer żądania: "+request.id:"Żądanie usunięcia konta zostało przyjęte. Numer: "+request.id);if(type==="DELETE_ACCOUNT")setDeleteConfirm("")}catch(e){setError(e instanceof ApiError?e.message:"Nie udało się utworzyć żądania.")}finally{setSaving(false)}}
 if(loading)return <div className="page"><div className="card review-card"><Loader2 className="spin"/><p>Wczytuję ustawienia…</p></div></div>;
 if(!profile)return <div className="page"><div className="card"><h1>Nie udało się wczytać ustawień</h1><p role="alert">{error}</p></div></div>;
 const activeWeeklyMinutes=(language==="de"?profile.germanWeeklyMinutes:profile.englishWeeklyMinutes)??profile.weeklyMinutes;
 return <div className="page"><div className="page-head"><div><p className="eyebrow">Ustawienia</p><h1>Ty kontrolujesz mentora</h1><p className="subtitle">Preferencje, pamięć, zgody i dane konta.</p></div></div>
  {(message||error)&&<div className="card flat" role="status" style={{marginBottom:16,color:error?"var(--danger)":"var(--teal)"}}>{error||message}</div>}
  <div className="settings-layout"><div className="card flat settings-nav">{([["learning","Nauka"],["memory","Pamięć AI"],["privacy","Prywatność"]] as [Tab,string][]).map(([key,label])=><button className={tab===key?"active":""} onClick={()=>{setTab(key);setMessage("");setError("")}} key={key}>{label}</button>)}</div>
   <section className="card">
    {tab==="learning"&&<><h2>Preferencje nauki</h2><div className="form">
     <div className="field"><label htmlFor="language-level">Twój poziom {language==="de"?"niemieckiego":"angielskiego"}</label><select id="language-level" className="select" value={level} onChange={e=>changeLevel(e.target.value as EnglishLevel)}>{ENGLISH_LEVELS.map(item=><option key={item.value} value={item.value}>{item.title}</option>)}</select><div className="muted" style={{fontSize:12,marginTop:6}}>{ENGLISH_LEVELS.find(item=>item.value===level)?.description}</div><Link className="button secondary" style={{marginTop:10,width:"fit-content"}} href="/placement-test">Wykonaj test poziomujący</Link></div>
     <div className="field"><label htmlFor="mentor-style">Styl mentora</label><select id="mentor-style" className="select" value={profile.mentorStyle} onChange={e=>setProfile({...profile,mentorStyle:e.target.value})}><option value="supportive">Wspierający</option><option value="neutral">Neutralny</option><option value="demanding">Wymagający</option></select></div>
     <div className="field"><label htmlFor="corrections">Intensywność korekt</label><select id="corrections" className="select" value={profile.correctionIntensity} onChange={e=>setProfile({...profile,correctionIntensity:Number(e.target.value)})}><option value={1}>Delikatna</option><option value={2}>Zbalansowana</option><option value={3}>Intensywna</option></select></div>
     <div className="field"><label htmlFor="weekly-minutes">Cel tygodniowy dla {language==="de"?"niemieckiego":"angielskiego"}</label><input id="weekly-minutes" className="input" type="number" min={10} max={840} step={5} value={activeWeeklyMinutes} onChange={e=>setProfile({...profile,[language==="de"?"germanWeeklyMinutes":"englishWeeklyMinutes"]:Number(e.target.value)})}/><span className="muted" style={{fontSize:12}}>Około {Math.max(1,Math.round(activeWeeklyMinutes/7))} min dziennie.</span></div>
     <button className="button primary" onClick={()=>void saveProfile()} disabled={saving}>{saving?<Loader2 className="spin" size={16}/>:<CheckCircle2 size={16}/>} Zapisz preferencje</button>
    </div></>}
    {tab==="memory"&&<><h2>Pamięć mentora</h2><p className="muted">Możesz zobaczyć i usunąć informacje wykorzystywane do personalizacji.</p><div className="lesson-list">{memories.map(memory=><div className="lesson" key={memory.id}><div className="lesson-icon"><ShieldCheck/></div><div><h3>{memory.value}</h3><p>{memory.type} · {memory.status}</p></div><button className="icon-btn" onClick={()=>void deleteMemory(memory.id)} aria-label="Usuń pamięć"><Trash2 size={17}/></button></div>)}</div>{!memories.length&&<div className="empty">Mentor nie przechowuje obecnie żadnych wspomnień.</div>}</>}
    {tab==="privacy"&&<><h2>Prywatność i zgody</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:18}}><Link className="button secondary" href="/privacy-policy">Polityka prywatności</Link><Link className="button secondary" href="/account-deletion">Publiczna strona usunięcia konta</Link></div>
     <Toggle label="Przetwarzanie rozmów przez AI" description="Wymagane do korzystania z mentora OpenAI." on={consents.AI_PROCESSING??false} click={()=>void setConsent("AI_PROCESSING",!(consents.AI_PROCESSING??false))}/>
     <Toggle label="Personalizacja planu i mentora" description="Pozwala dopasowywać ćwiczenia do Twojej historii." on={consents.PERSONALIZATION??false} click={()=>void setConsent("PERSONALIZATION",!(consents.PERSONALIZATION??false))}/>
     <Toggle label="Analityka produktu" description="Pomaga wykrywać problemy i ulepszać aplikację." on={consents.ANALYTICS??false} click={()=>void setConsent("ANALYTICS",!(consents.ANALYTICS??false))}/>
     <Toggle label="Czasowe przechowywanie audio" description="Nie jest potrzebne dla darmowego trybu mikrofonu w przeglądarce." on={consents.AUDIO_RETENTION??false} click={()=>void setConsent("AUDIO_RETENTION",!(consents.AUDIO_RETENTION??false))}/>
     <Toggle label="Wiadomości marketingowe" description="Opcjonalne informacje o nowościach." on={consents.MARKETING??false} click={()=>void setConsent("MARKETING",!(consents.MARKETING??false))}/>
     <div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:24}}><button className="button secondary" onClick={()=>void privacyRequest("EXPORT")} disabled={saving}><Download size={15}/> Eksportuj moje dane</button></div>
     <div className="coach-tip" style={{marginTop:24}}><h3>Usunięcie konta i danych</h3><p>To żądanie rozpoczyna bezpieczny proces usunięcia. Wpisz <b>USUŃ</b>, aby potwierdzić.</p><input className="input" value={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.value)} placeholder="Wpisz USUŃ"/><button className="button danger" style={{marginTop:10}} disabled={deleteConfirm!=="USUŃ"||saving} onClick={()=>void privacyRequest("DELETE_ACCOUNT")}><Trash2 size={15}/> Złóż żądanie usunięcia konta</button></div>
    </>}
   </section>
  </div>
 </div>;
}
function Toggle({label,description,on,click}:{label:string;description:string;on:boolean;click():void}){return <div className="toggle-row"><div><b>{label}</b><div className="muted" style={{fontSize:12,marginTop:3}}>{description}<br/>{on?"Włączone":"Wyłączone"}</div></div><button className={"toggle "+(on?"on":"")} onClick={click} role="switch" aria-checked={on} aria-label={label}/></div>}
