"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Sparkles } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useState } from "react";
import { useAuth } from "@/lib/auth";
import { ApiError } from "@/lib/api-client";

const schema=z.object({email:z.string().email("Podaj poprawny adres e-mail"),password:z.string().min(12,"Hasło musi mieć co najmniej 12 znaków")}); type Form=z.infer<typeof schema>;
export default function SignIn(){const router=useRouter();const {login}=useAuth();const [serverError,setServerError]=useState("");const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema)});const submit=handleSubmit(async data=>{setServerError("");try{await login(data.email,data.password);router.push("/dashboard")}catch(error){setServerError(error instanceof ApiError&&error.status===401?"Nieprawidłowy e-mail lub hasło.":error instanceof Error?error.message:"Logowanie nie powiodło się.")}});return <div className="auth-page"><section className="auth-art"><div className="brand" style={{padding:0,color:"white"}}><span className="brand-mark" style={{background:"rgba(255,255,255,.18)"}}><Sparkles/></span>Fluentia</div><div><span className="pill">Twój codzienny mentor AI</span><h1>Mów odważniej. Brzmij naturalniej.</h1><p style={{maxWidth:550,lineHeight:1.7,color:"rgba(255,255,255,.8)"}}>Praktyczne rozmowy, precyzyjny feedback i plan dopasowany do Twojego poziomu.</p></div><small>AI może się mylić. To Ty kontrolujesz pamięć i dane.</small></section><main className="auth-panel"><div className="auth-box"><Link className="brand" href="/"><span className="brand-mark"><Sparkles/></span>Fluentia</Link><h1>Witaj ponownie</h1><p className="subtitle" style={{marginBottom:25}}>Zaloguj się do swojego konta.</p><form className="form" onSubmit={submit}><div className="field"><label htmlFor="email">E-mail</label><input className="input" id="email" type="email" autoComplete="email" {...register("email")}/>{errors.email&&<span className="error">{errors.email.message}</span>}</div><div className="field"><label htmlFor="password">Hasło</label><input className="input" id="password" type="password" autoComplete="current-password" {...register("password")}/>{errors.password&&<span className="error">{errors.password.message}</span>}</div>{serverError&&<div className="error" role="alert">{serverError}</div>}<button className="button primary" disabled={isSubmitting}>{isSubmitting?"Logowanie…":"Zaloguj się"}</button></form><p className="muted" style={{textAlign:"center",fontSize:13,marginTop:22}}>Nie masz konta? <Link href="/sign-up" style={{color:"var(--primary)",fontWeight:700}}>Utwórz konto</Link></p></div></main></div>}